- name: push-to-firefly
  hosts: "firefly-f"
  gather_facts: False
  vars:
    home: /home/firefly
  tasks:
  - name: Synchronization api source
    tags:
      - sync
    synchronize:
      src: ./api/src/
      dest: "{{ home }}/bell/api/src/"
      archive: yes
      delete: yes
      checksum: yes
  - name: Synchronization api file
    tags:
      - sync
    synchronize:
      src: ./api/static/
      dest: "{{ home }}/bell/api/static/"
      archive: yes
      delete: yes
      checksum: yes
  - name: Synchronization api
    tags:
      - sync
    synchronize:
      src: ./api/Cargo.toml
      dest: "{{ home }}/bell/api/Cargo.toml"
  - name: Synchronization fe
    tags:
      - sync
    synchronize:
      src: ./fe/resources/
      dest: "{{ home }}/bell/fe/resources/"
      delete: yes
  - name: Synchronization python
    tags:
      - sync
    synchronize:
      src: ./python/
      dest: "{{ home }}/bell/python/"
      delete: yes
  - name: Synchronization restart-api
    tags:
      - sync
    synchronize:
      src: ./restart-api.sh
      dest: "{{ home }}/bin/restart-api.sh"
  - name: Synchronization restart-fe
    tags:
      - sync
    synchronize:
      src: ./restart-fe.sh
      dest: "{{ home }}/bin/restart-fe.sh"

  - name: build bell.api
    shell:  "{{ home }}/.cargo/bin/cargo build"
    tags:
      - build
    async: 1000
    poll: 0
    args:
      chdir: "{{ home }}/bell/api"
      executable:  /bin/bash
  - name: restart bell.api
    shell:  "{{ home }}/bin/restart-api.sh"
    tags:
      - run
      - api
    async: 2592000
    poll: 5
    args:
      chdir: "{{ home }}/bell/api"
      executable:  /bin/bash
  - name: restart bell.fe
    shell:  "{{ home }}/bin/restart-fe.sh"
    tags:
      - run
      - fe
    async: 2592000
    poll: 5
    args:
      chdir: "{{ home }}/bell/fe"
      executable:  /bin/bash
  - name: install python lib
    shell: make install
    tags:
      - python
    async: 2592000
    poll: 5
    args:
      chdir: "{{ home }}/python"
      executable:  /bin/bash
